services:
  spoolman:
    image: donkie/spoolman:test
    environment:
      - SPOOLMAN_DATA_FILE=/data/spoolman.json
      - SPOOLMAN_LOGGING_LEVEL=INFO
    volumes:
      - spoolman_data:/data
    security_opt:
      - no-new-privileges:true
  tester:
    image: donkie/spoolman-tester:latest
    volumes:
      - ./tests:/tester/tests
    security_opt:
      - no-new-privileges:true
    depends_on:
      - spoolman

volumes:
  spoolman_data:
