services:
  spoolman:
    image: donkie/spoolman:test
    environment:
      - SPOOLMAN_LOGGING_LEVEL=INFO
      - TZ=Europe/Stockholm
    security_opt:
      - no-new-privileges:true
  tester:
    image: donkie/spoolman-tester:latest
    volumes:
      - ./tests:/tester/tests
    security_opt:
      - no-new-privileges:true
    depends_on:
      - spoolman
