services:
  spoolman:
    image: spoolman-light:latest
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - spoolman_data:/data
    environment:
      - SPOOLMAN_DATA_FILE=/data/spoolman.json
      # - SPOOLMAN_PORT=8000
    security_opt:
      - no-new-privileges:true

volumes:
  spoolman_data:
