name: CI

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master

permissions:
  contents: read
  packages: read

env:
  GHCR_IMAGE: donkie/spoolman

jobs:
  #
  # Rust type-check and lint
  #
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: cargo check (types)
        run: cargo check -p spoolman-types

      - name: cargo check (server)
        run: cargo check -p spoolman-server

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: cargo clippy
        run: cargo clippy -p spoolman-types -p spoolman-server -- -D warnings

  #
  # Build native image
  # Only push to cache on non-PR runs; PRs build without cache push
  #
  build-amd64:
    needs: [check]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Spoolman
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          tags: ${{ env.GHCR_IMAGE }}:test
          outputs: type=docker,dest=/tmp/spoolman.tar
          cache-from: type=registry,ref=ghcr.io/${{ env.GHCR_IMAGE }}:buildcache-amd64
          cache-to: type=registry,ref=ghcr.io/${{ env.GHCR_IMAGE }}:buildcache-amd64,mode=max

      # Separate build for pull requests since PRs don't have access to store cache
      - name: Build Spoolman (PR)
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          tags: ${{ env.GHCR_IMAGE }}:test
          outputs: type=docker,dest=/tmp/spoolman.tar
          cache-from: type=registry,ref=ghcr.io/${{ env.GHCR_IMAGE }}:buildcache-amd64

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: spoolman-image
          path: /tmp/spoolman.tar
  #
  # Build arm64 image
  # Don't run this for pull requests
  # Only push to buildcache and let release job push to registry
  #
  build-arm64:
    if: ${{ github.event_name != 'pull_request' }}
    needs: [check]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and cache Docker image
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          platforms: linux/arm64
          cache-from: type=registry,ref=ghcr.io/${{ env.GHCR_IMAGE }}:buildcache-arm64
          cache-to: type=registry,ref=ghcr.io/${{ env.GHCR_IMAGE }}:buildcache-arm64,mode=max
  #
  # Build arm/v7 image
  # Don't run this for pull requests
  # Only push to buildcache and let release job push to registry
  #
  build-armv7:
    if: ${{ github.event_name != 'pull_request' }}
    needs: [check]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and cache Docker image
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          platforms: linux/arm/v7
          cache-from: type=registry,ref=ghcr.io/${{ env.GHCR_IMAGE }}:buildcache-armv7
          cache-to: type=registry,ref=ghcr.io/${{ env.GHCR_IMAGE }}:buildcache-armv7,mode=max
  #
  # Release images to GHCR and Docker Hub if CI passes
  # Don't run this for pull requests
  #
  publish-images:
    if: ${{ github.event_name != 'pull_request' }}
    needs: [check, clippy, build-amd64, build-arm64, build-armv7]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for GHCR
        id: meta-ghcr
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            ghcr.io/${{ env.GHCR_IMAGE }}
          tags: |
            type=edge
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Extract metadata (tags, labels) for Docker Hub
        id: meta-dh
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            ${{ vars.REMOTE_REGISTRY_URL }}/${{ vars.REMOTE_REGISTRY_NAMESPACE }}/${{ vars.REMOTE_REGISTRY_REPOSITORY }}
          tags: |
            type=edge
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Log in to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ vars.REMOTE_REGISTRY_URL }}
          username: ${{ secrets.REMOTE_REGISTRY_USERNAME }}
          password: ${{ secrets.REMOTE_REGISTRY_PASSWORD }}

      - name: Store git commit and build date
        run: |
          echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
          echo "BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "$GITHUB_ENV"

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ steps.meta-ghcr.outputs.tags }}
            ${{ steps.meta-dh.outputs.tags }}
          labels: ${{ steps.meta-ghcr.outputs.labels }}
          build-args: |
            GIT_COMMIT
            BUILD_DATE
          cache-from: |
            type=registry,ref=ghcr.io/${{ env.GHCR_IMAGE }}:buildcache-amd64
            type=registry,ref=ghcr.io/${{ env.GHCR_IMAGE }}:buildcache-arm64
            type=registry,ref=ghcr.io/${{ env.GHCR_IMAGE }}:buildcache-armv7
  #
  # Create Github Release if CI was triggered by a tag
  #
  publish-release:
    if: ${{ (github.event_name != 'pull_request') && startsWith(github.event.ref, 'refs/tags/v') }}
    needs: [publish-images]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "⚠️ TODO ⚠️"
